### ISSUE TITLE
Header style issue

### ISSUE THREAD

**Issue by k0msenapati** [amrit03b/TravelTales#1]
When I opened write.html in a web browser it was something like this : 
![image](https://github.com/amrit03b/TravelTales/assets/92045934/0a33c9f7-3e62-4b9b-9da5-4b28c3ef8e23)

I can change this style to make it look like this : 
![image](https://github.com/amrit03b/TravelTales/assets/92045934/a5df761a-7c19-4866-8f65-ca214ca59807)

You can assign me this issue.

**Comment by amrit03b** [comment]
Assigned @kom-senapati
