### ISSUE TITLE
Adding Search Functionality

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#14]
Implement a search bar to allow users to search for specific travel journals based on keywords, destinations, or user names.

**Comment by priyanshu-gupta0503** [comment]
hey@amrit03b  I would like to contribute on this pls assign this to me

**Comment by prithu12** [comment]
hey can you assign to me

**Comment by amrit03b** [comment]
> hey@amrit03b I would like to contribute on this pls assign this to me

Assigned.

**Comment by amrit03b** [comment]
> hey can you assign to me

Assigned @prithu12

**Comment by harshit-m007** [comment]
hey there, can you assign this task to me

**Comment by amrit03b** [comment]
> hey there, can you assign this task to me

Assigned @harshit-m007
