### ISSUE TITLE
Enabling Advanced Editing Options

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#17]
Provide users with more sophisticated text editing tools, enabling them to format their travel journals creatively.

**Comment by harshit-m007** [comment]
@amrit03b please assign this issue to me

**Comment by amrit03b** [comment]
> @amrit03b please assign this issue to me

Assigned @harshit-m007

**Comment by amrit03b** [comment]
> @amrit03b please assign this issue to me

Hey, are you still working on this?

**Comment by harshit-m007** [comment]
hey, yes i will try to do it by tomorrow

**Comment by amrit03b** [comment]
> hey, yes i will try to do it by tomorrow

Ok.
