### ISSUE TITLE
Making the Read and Write in Centre of Home Page

### ISSUE THREAD

**Issue by 7sohamd** [amrit03b/TravelTales#18]
Making the Read and Write in Centre of Home Page so that it looks nice.

**Comment by shahil-afroz** [comment]
can you assign this to me?

**Comment by MeetD99** [comment]
Hi, I can work on this Issue, Can you assign it to me please?

**Comment by amrit03b** [comment]
> can you assign this to me?

Hey, this issue is closed for now but feel free to create a new issue to work on adding any new features or updating the exsisting ones.

**Comment by amrit03b** [comment]
> Hi, I can work on this Issue, Can you assign it to me please?

Hey, this issue is closed for now but feel free to create a new issue to work on adding any new features or updating the exsisting ones.
