### ISSUE TITLE
sign up button not working 

### ISSUE THREAD

**Issue by k0msenapati** [amrit03b/TravelTales#2]
![image](https://github.com/amrit03b/TravelTales/assets/92045934/9ad4edb3-2836-4ac4-937c-8dd15a786c93)

A signup popup can be created so that one can sign up.

**Comment by harshsinghcs** [comment]
I want to work on that please assign me

**Comment by amrit03b** [comment]
> I want to work on that please assign me

Assigned @harshsinghcs

**Comment by amrit03b** [comment]
> ![image](https://user-images.githubusercontent.com/92045934/270665537-9ad4edb3-2836-4ac4-937c-8dd15a786c93.png)
> 
> A signup popup can be created so that one can sign up.

Work on it.

**Comment by k0msenapati** [comment]
I created the frontend part of the form.
![image](https://github.com/amrit03b/TravelTales/assets/92045934/86dfa713-facf-4231-8971-1b4dbbcb3c80)
![image](https://github.com/amrit03b/TravelTales/assets/92045934/21a6a006-50c5-4cfa-a6bc-4ae534269ceb)
