### ISSUE TITLE
Changing Font Styling and fixing some bugs

### ISSUE THREAD

**Issue by 7sohamd** [amrit03b/TravelTales#30]
Please Assign Me

**Comment by 7sohamd** [comment]
please

**Comment by amrit03b** [comment]
> Please Assign Me

Assigned @7sohamd

**Comment by harshsinghcs** [comment]
kindly assign this issue to me also @amrit03b under hacktoberfest

**Comment by amrit03b** [comment]
> kindly assign this issue to me also @amrit03b under hacktoberfest

Sorry, it was supposed to be closed as it is already fixed by @7sohamd.
