### ISSUE TITLE
Minor bug fixes

### ISSUE THREAD

**Issue by 7sohamd** [amrit03b/TravelTales#33]

**Comment by harshsinghcs** [comment]
@amrit03b kindly assign this issue to me

**Comment by 7sohamd** [comment]
kindly assign me this issue

**Comment by amrit03b** [comment]
> kindly assign me this issue

Assigned @7sohamd

**Comment by amrit03b** [comment]
> @amrit03b kindly assign this issue to me

It has already been assigned. Kindly create a new issue suggesting some changes or work upon existing issues.

**Comment by harshsinghcs** [comment]
> > @amrit03b kindly assign this issue to me
> 
> It has already been assigned. Kindly create a new issue suggesting some changes or work upon existing issues.

ok sir

**Comment by harshit-m007** [comment]
@amrit03b I found a minor bug. Can i contribute?

**Comment by amrit03b** [comment]
> @amrit03b I found a minor bug. Can i contribute?

Yes, sure. Just create a new issue stating the bug you found and make the PR solving the issue.
