### ISSUE TITLE
Making Home Page Responsive

### ISSUE THREAD

**Issue by GauravGupta993** [amrit03b/TravelTales#40]
I want to make the home page responsive. Here is a screenshot of the current home page on mobile. 
![WhatsApp Image 2023-10-13 at 00 10 54_feb317e8](https://github.com/amrit03b/TravelTales/assets/123398315/d0f0d4a4-5f37-41a7-b7db-2419f0c664a1)

**Comment by GauravGupta993** [comment]
I would like to contribute to this project by working on this issue.

**Comment by amrit03b** [comment]
> I would like to contribute to this project by working on this issue.

Great. Assigned to you @GauravGupta993

**Comment by amrit03b** [comment]
> I would like to contribute to this project by working on this issue.

Are you still working on this issue? @GauravGupta993

**Comment by GauravGupta993** [comment]
Yeah. Will complete within 2 days

> > I would like to contribute to this project by working on this issue.
> 
> Are you still working on this issue? @GauravGupta993

**Comment by amrit03b** [comment]
> Yeah. Will complete within 2 days
> 
> > > I would like to contribute to this project by working on this issue.
> > 
> > 
> > Are you still working on this issue? @GauravGupta993

Ok👍
