### ISSUE TITLE
Improving scroll bar look. 

### ISSUE THREAD

**Issue by GauravGupta993** [amrit03b/TravelTales#41]
Changing current default scroll bar:
![image](https://github.com/amrit03b/TravelTales/assets/123398315/a90d2a63-8e6a-4221-a84c-d5deafef7ea2)
To new scroll bar:
![image](https://github.com/amrit03b/TravelTales/assets/123398315/292a2ab5-5684-4b4f-a507-1171c190ba86)

**Comment by GauravGupta993** [comment]
I would like to work on this issue as well.

**Comment by amrit03b** [comment]
> I would like to work on this issue as well.

Assigned.

**Comment by GauravGupta993** [comment]
Changed the scrollbar for all existing pages. The CSS code for the scrollbar will need to be added to all pages CSS that are created.

**Comment by amrit03b** [comment]
> Changed the scrollbar for all existing pages. The CSS code for the scrollbar will need to be added to all pages CSS that are created.

Great
