### ISSUE TITLE
Creating Login/Signup pop-up when clicked on Write

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#47]
Whenever user clicks on the Write Page a pop up should come asking them to login/signup before Writing their travel journals.
Login/Signup page is already created, just make sure it asks the user to login before they can write anything.

**Comment by madmaxWMFU** [comment]
Hi! I can try this) Can you assign it for me?

**Comment by amrit03b** [comment]
> Hi! I can try this) Can you assign it for me?

Assigned @madmaxWMFU
