### ISSUE TITLE
Adding Animation to the Title 'TravelTales'

### ISSUE THREAD

**Issue by Dhavisco** [amrit03b/TravelTales#49]
I want to contribute by adding animation to the TravelTales logo when the page is opened or reloaded and better interactivity.

@amrit03b kindly assign this to me

**Comment by amrit03b** [comment]
> I want to contribute by adding animation to the TravelTales logo when the page is opened or reloaded and better interactivity.
> 
> @amrit03b kindly assign this to me

Assigned. @Dhavisco
