### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by rahulkundu1209** [amrit03b/TravelTales#56]
In the home page in read and write section the images are not being displayed properly. Display valid images in place of Card 1 and Card 2.

<img width="814" alt="image" src="https://github.com/amrit03b/TravelTales/assets/121861377/f35604f6-ca7b-491e-922c-7ecb025cb290">

Assign me this issue, I can solve it.

**Comment by amrit03b** [comment]
> In the home page in read and write section the images are not being displayed properly. Display valid images in place of Card 1 and Card 2.
> 
> <img alt="image" width="814" src="https://user-images.githubusercontent.com/121861377/275420994-f35604f6-ca7b-491e-922c-7ecb025cb290.png">
> Assign me this issue, I can solve it.

It was a temporary issue since I was updating some file locations. Please create a different issue or work on existing ones.
