### ISSUE TITLE
To make the Text more visible.

### ISSUE THREAD

**Issue by pradyumna14** [amrit03b/TravelTales#57]
Dear maintainer,
Due to the background images, the texts has been faded as the color of both are not matching,
Please assign me this issue so that i can resolve this.
Thank you

![image](https://github.com/amrit03b/TravelTales/assets/126577744/13e82736-d77a-4322-9fdc-f5824d2abbc7)

**Comment by amrit03b** [comment]
> Dear maintainer, Due to the background images, the texts has been faded as the color of both are not matching, Please assign me this issue so that i can resolve this. Thank you
> 
> ![image](https://user-images.githubusercontent.com/126577744/275498858-13e82736-d77a-4322-9fdc-f5824d2abbc7.png)

Assigned to you. @pradyumna14
