### ISSUE TITLE
Shift the 'Write' and 'Read' text to the middle of the cards

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#62]
![issue1](https://github.com/amrit03b/TravelTales/assets/116283061/0d7f5b4a-3697-4c52-a2f1-e8ecbe8769f0)

Shift the 'Write' and 'Read' text to the middle of the cards.

**Comment by jude-san** [comment]
Hi @amrit03b  can I take this?

**Comment by mmehraa** [comment]
Hey! I have created a pull request solving this issue. Have a look at it.
Thanks

**Comment by amrit03b** [comment]
> Hi @amrit03b can I take this?

Hi @jude-san , this issue is closed for now. Would you like to work on some other issues?

**Comment by jude-san** [comment]
> > Hi @amrit03b can I take this?
> 
> Hi @jude-san , this issue is closed for now. Would you like to work on some other issues?

yes
