### ISSUE TITLE
Adding About Us Page 

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#63]
Create an 'About Us' page containing details about TravelTales (you can copy it from Readme) and add it to the footer of home page and  the side navbar.

**Comment by sid172014** [comment]
Hey @amrit03b i hope you're doing good , Can you please assign this issue to me?

**Comment by Abishkardhenga** [comment]
i would love to work on this issue can you provide design of the  page

**Comment by amrit03b** [comment]
> Hey @amrit03b i hope you're doing good , Can you please assign this issue to me?

Assigned to you @sid172014

**Comment by amrit03b** [comment]
> i would love to work on this issue can you provide design of the page

Hi @Abishkardhenga , would you like to work on any other issues as this issue is already assigned.

**Comment by Abishkardhenga** [comment]
@amrit03b  ok sir

**Comment by amrit03b** [comment]
> @amrit03b ok sir

@Abishkardhenga  Would you like to work on issue #67 ?

**Comment by Abishkardhenga** [comment]
ok I  can

**Comment by amrit03b** [comment]
> ok I can

Comment in the issue #67  for assignment.

**Comment by ShrujanaReddy** [comment]
Can you assign this issue to me, since the work is still pending?

**Comment by amrit03b** [comment]
> Can you assign this issue to me, since the work is still pending?

Sure, assigned to you @ShrujanaReddy
