### ISSUE TITLE
Improve Transition Timing for Buttons

### ISSUE THREAD

**Issue by KunalBhat55** [amrit03b/TravelTales#64]
Address the transition timing for buttons, it's currently too long, affecting user experience.

You can check it on the website when you hover over the buttons.

**Comment by amrit03b** [comment]
> Address the transition timing for buttons, it's currently too long, affecting user experience.
> 
> You can check it on the website when you hover over the buttons.

Assigned to you @KunalBhat55

**Comment by KunalBhat55** [comment]
> > Address the transition timing for buttons, it's currently too long, affecting user experience.
> > You can check it on the website when you hover over the buttons.
> 
> Assigned to you @KunalBhat55

Sure!
