### ISSUE TITLE
Bringing 'TravelTales:)' to the middle in Write and Read pages and adding the same animation as in Home page. 

### ISSUE THREAD

**Issue by amrit03b** [amrit03b/TravelTales#67]
Bring 'TravelTales:)' logo to the middle in Write and Read pages and add the same animation as present in the Home page.

**Comment by xshubheex** [comment]
can i work on this issue

**Comment by amrit03b** [comment]
> can i work on this issue

Sure. Assigned to you @xshubheex

**Comment by amrit03b** [comment]
> can i work on this issue

Are you still working on this issue? @xshubheex

**Comment by rajvinder-kaur** [comment]
i can work on this issue @amrit03b

**Comment by amrit03b** [comment]
> i can work on this issue @amrit03b 
> 

Sure. Assigned @rajvinder-kaur

**Comment by rajvinder-kaur** [comment]
@amrit03b take a look at the fixed version
