### ISSUE TITLE
Privacy Policy Addition

### ISSUE THREAD

**Issue by anuragverma108** [amrit03b/TravelTales#70]

**Comment by anuragverma108** [comment]
Hello Maintainer @amrit03b . I want to add Privacy Policy to your website. Kindly assign me this issue .

**Comment by amrit03b** [comment]
> Hello Maintainer @amrit03b . I want to add Privacy Policy to your website. Kindly assign me this issue .

Assigned to you @anuragverma108 .

**Comment by ShrujanaReddy** [comment]
Hey! I would like to work on this.

**Comment by amrit03b** [comment]
> Hey! I would like to work on this.

Assigned to you @ShrujanaReddy
