### ISSUE TITLE
Authorization can be bypassed by changing url.  

### ISSUE THREAD

**Issue by GauravGupta993** [amrit03b/TravelTales#80]
When on home and accessing read or write through navbar, it is asking for authorization which is fine. But the authorization can be bypassed by changing url like replacing index.html in url with write.html. For example- when opening site we are initially on url https://amrit03b.github.io/TravelTales/index.html but by manually changing url to https://amrit03b.github.io/TravelTales/write.html no authorization is required.

**Comment by amrit03b** [comment]
> When on home and accessing read or write through navbar, it is asking for authorization which is fine. But the authorization can be bypassed by changing url like replacing index.html in url with write.html. For example- when opening site we are initially on url https://amrit03b.github.io/TravelTales/index.html but by manually changing url to https://amrit03b.github.io/TravelTales/write.html no authorization is required.

Assigned to you @GauravGupta993
